--- #YAML:1.0
name:                Bundle-PDF
version:             0.03
abstract:            A bundle to install PDF modules and dependencies
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kevin W. Henwood <Khen1950fx@aol.com>
